GET http://127.0.0.1:4000
###

POST http://127.0.0.1:4000
content-type: application/json

{
    "name": "Arba",
    "email": "arba@gmail.com"
}
###
DELETE http://127.0.0.1:4000/Sandi
###
PUT http://127.0.0.1:4000
content-type: application/json

{
    "name": "Putra",
    "email": "arba@gmail.com"
}